# docker-compose.yml
#
# This file is the base configuration for the Docker Compose setup.
# It defines the volumes and networks that are shared across all services.  

volumes:
  radem_data:
    driver: local
  grafana_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config_data:
    driver: local

networks:
  radem_network:
    driver: bridge

services:
  app:
    extends:
      file: ./docker-compose/docker-compose.app.yml
      service: app

  cadvisor:
    extends:
      file: ./docker-compose/docker-compose.cadvisor.yml
      service: cadvisor

  node-exporter:
    extends:
      file: ./docker-compose/docker-compose.node-exporter.yml
      service: node-exporter

  prometheus:
    extends:
      file: ./docker-compose/docker-compose.prometheus.yml
      service: prometheus

  grafana:
    extends:
      file: ./docker-compose/docker-compose.grafana.yml
      service: grafana

  influxdb:
    extends:
      file: ./docker-compose/docker-compose.influxdb.yml
      service: influxdb
