global:
  scrape_interval: 5s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - radem_cadvisor:8080
  - job_name: node_exporter
    static_configs:
      - targets:
          - radem_node_exporter:9100
