# default.yaml
#
# More resources on Grafana data sources:
# - https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
#
apiVersion: 1

datasources:
  - name: Radem
    type: influxdb
    access: proxy
    url: ${URL_INFLUXDB}
    uid: radem_influxdb_datasource
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: ${INFLUXDB_PASSWORD}
      token: ${INFLUXDB_TOKEN}
  - name: Irem
    type: influxdb
    access: proxy
    url: ${URL_INFLUXDB}
    uid: irem_influxdb_datasource
    isDefault: false
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_IREM_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: ${INFLUXDB_PASSWORD}
      token: ${INFLUXDB_TOKEN}
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${URL_PROMETHEUS}
    isDefault: false
    editable: true
