- name: Install Docker (Debian)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker.io
    - docker-compose
    - python3-pip
  when: ansible_os_family == 'Debian'

- name: Add repository (RedHat)
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker YUM repo
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
  when: ansible_os_family == 'RedHat'

- name: Install pip (RedHat)
  ansible.builtin.yum:
    name: python3-pip
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install pip (Debian)
  ansible.builtin.apt:
    name: python3-pip
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker

- name: Install Docker (RedHat)
  ansible.builtin.yum:
    name: docker-ce, docker-ce-cli, containerd.io
    state: present
  when: ansible_os_family == 'RedHat'

- name: Start and enable Docker service
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: true

- name: Create a docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present
