grafana_port: 80
grafana_url: "http://localhost:{{ grafana_port }}"
grafana_admin_user: admin
grafana_admin_password: "grafana_admin_password"
grafana_viewer_user: user
grafana_viewer_password: "grafana_viewer_password"
grafana_viewer_user_email: "viewer@domain.com"
grafana_docker_container_name: grafana

datasource_name: Influxdb
