- name: Create persistent /app directory on host
  ansible.builtin.file:
    path: /app
    state: directory
    mode: "0755"

- name: Synchronize files to /app directory
  synchronize:
    src: "../files/"
    dest: "/app"
    delete: yes

- name: Run a Docker container based on the Python image
  community.docker.docker_container:
    name: radem
    image: python:3.10
    detach: false
    env:
      FTP_USER: "{{ FTP_USER }}"
      FTP_PASSWORD: "{{ FTP_PASSWORD }}"
      CDF_LIB: "{{ CDF_LIB }}"
      INFLUXDB_TOKEN: "{{ influx_token }}"
    volumes:
      - /app:/app
    command: "tail -f /dev/null"
    # command: "bash -c 'cd /app/radem-notebooks && ./install.sh'"
    networks:
      - name: "{{ docker_network_name }}"
    state: started
